### ISSUE TITLE
Is it possible that this plugin won't work with gatsby v2.x

### ISSUE THREAD

**Issue by KilianSSL** [jacobmischka/gatsby-plugin-copy-files#3]
i'm using gatsby v2.x but the copy-files plugin won't work for me

    "gatsby-plugin-copy-files": "^1.0.2",
    "gatsby-plugin-manifest": "^2.0.24",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.10",
    "gatsby-plugin-sass": "^2.0.11",
    "gatsby-source-filesystem": "^2.0.33",
    "gatsby-transformer-yaml": "^2.1.12",

gatsby-config.js

    {
      resolve: 'gatsby-plugin-copy-files',
      options: {
        source: `${__dirname}/src/dynamic/send.php`,
        destination: '/dynamic'
      }
    },

Is it maybe not made for v2?

**Comment by jacobmischka** [comment]
It is very possible! I honestly haven't looked at or used this plugin in ages, ha. I'll try to take a look soon!

**Comment by KilianSSL** [comment]
Well, turns out it works as expected, i only had to add the `gatsby-source-filesystem` Block in the config.


    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `./src/dynamic/`,
      },
    },

Maybe something that could be stated more clearly in the README.md

**Comment by jacobmischka** [comment]
Ah, glad to hear it. The README does specify that `gatsby-source-filesystem` is required, please feel free to create a PR if there's some additional text you can think of that would have made that clearer.
